AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Enabled: false
