development:
  clients:
    default:
      database: library_development
      hosts:
        - localhost:27017
      options:

        server_selection_timeout: 1

  options:
  driver_options:

test:
  clients:
    default:
      database: library_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
